server:
  port: 8888
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  shutdown: graceful
  tomcat:
    relaxed-query-chars: [ '{','}','?','\','|','[',']' ]

spring:
  profiles:
    active: local
  application:
    name: minio-storage-service
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  messages:
    basename: language/message
    encoding: UTF-8
    cache-duration: -1
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    time-zone: "Asia/Ho_Chi_Minh"
    default-property-inclusion: non_null
  servlet:
    multipart:
      # Cho phép tải lên nhiều phần
      enabled: true
      # Ngưỡng sau đó các tệp được ghi vào đĩa.
      file-size-threshold: 2KB
      # Tổng kích thước tệp không được vượt quá 500MB.
      max-file-size: 500MB
      # Tổng kích thước yêu cầu cho một multipart/form-data không được vượt quá 510MB.
      max-request-size: 510MB

springdoc:
  swagger-ui:
    path: /minio-storage-service-documentation
    tryItOutEnabled: true
    filter: true
    # API sẽ được sắp xếp theo phương thức thực hiện (GET, POST, PUT, DELETE, vv).
    operationsSorter: method
    # Các nhóm sẽ được sắp xếp theo thứ tự chữ cái.
    tagsSorter: alpha
  api-docs:
    path: /minio-storage-service-api-docs
  packages-to-scan: com.minio.storage.api

logging:
  level:
    io.eventuate: debug
    io.eventuate.tram: trace
    org.springframework.orm.jpa: info
    org.hibernate.SQL: debug
    org.springframework.jdbc.core: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

minio:
  openapi:
    dev-url: http://localhost:8888
    prod-url: https://minio-storage-api.com
  bucket:
    name: ${MINIO_BUCKET_NAME:minio-storage-service}
  default:
    folder: /
  access:
    key: ${MINIO_ACCESS_KEY:LSKwqEWJl85j2aW73WEF}
    secret: ${MINIO_ACCESS_SECRET:jfgFEkfkG1bjJReyzofIweuo0mpkNOMhJiEToRwE}
  endpoint:
    url: ${MINIO_URL:http://localhost}
    port: ${MINIO_PORT:9000}
    secure: ${MINIO_SECURE:false}
  file-size: ${MINIO_FILE_SIZE:1073741824} # Maximum file size