server:
  port: 8888
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  shutdown: graceful
  tomcat:
    relaxed-query-chars: [ '{','}','?','\','|','[',']' ]

spring:
  application:
    name: minio-storage-service
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  messages:
    basename: language/message
    encoding: UTF-8
    cache-duration: -1
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    time-zone: "Asia/Ho_Chi_Minh"
    default-property-inclusion: non_null
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Total file size cannot exceed 20MB
      max-file-size: 500MB
      # Total request size for a multipart/form-data cannot exceed 200MB
      max-request-size: 510MB

logging:
  level:
    io.eventuate: debug
    io.eventuate.tram: trace
    org.springframework.orm.jpa: info
    org.hibernate.SQL: debug
    org.springframework.jdbc.core: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

minio:
  bucket:
    name: ${MINIO_BUCKET_NAME:minio-storage-service}
  default:
    folder: /
  access:
    key: ${MINIO_ACCESS_KEY:tx49JFX7tZnjEDuWdact}
    secret: ${MINIO_ACCESS_SECRET:6MxkUcyzy1xeClwjlcNSRUfXgpQq7D0f4DmyZsyL}
  endpoint:
    url: ${MINIO_URL:http://14.225.211.86}
    port: ${MINIO_PORT:9000}
    secure: ${MINIO_SECURE:false}
  file-size: ${MINIO_FILE_SIZE:1073741824} # Maximum file size