spring:
  application:
    name: minio-storage-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 4953

minio:
  bucket:
    name: ${MINIO_BUCKET_NAME:minio-storage-service}
  default:
    folder: /
  access:
    key: ${MINIO_ACCESS_KEY:tx49JFX7tZnjEDuWdact}
    secret: ${MINIO_ACCESS_SECRET:6MxkUcyzy1xeClwjlcNSRUfXgpQq7D0f4DmyZsyL}
  url: ${MINIO_URL:http://14.225.211.86:9000}